name: build-and-push

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Docker buildx
      run: |
        docker buildx create --use
    - name: Build and Push
      run: |
        docker buildx build \
        --platform linux/arm64/v8,linux/amd64 \
        --tag reverie89/image-processor \
        --push .
