name: build-and-push

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker buildx build --platform linux/arm64/v8,linux/amd64 -t reverie89/image-processor . --push
